### ISSUE TITLE
Syntax error for enum_field example

### ISSUE THREAD

**Issue by Meldanor** [Crecto/docs#1]
The [example for Enums](https://github.com/Crecto/docs/blob/master/crecto-model/README.md#enum-fields) given in the documentation is not working with crecto 0.9:

```crystal
    schema "vehicles" do
        enum_field, :state, State
        enum_field, :make, Make, column_name: "vehicle_type", column_type: Int32
    end
```

The commas behind `enum_field` are wrong and must be removed.

**Comment by fridgerator** [comment]
fixed via https://github.com/Crecto/docs/commit/a8a2880c860a6ae9f7bfb236c062658d06508710
