### ISSUE TITLE
Join example correct?

### ISSUE THREAD

**Issue by mmKALLL** [Crecto/docs#2]
Hi, I was reading the docs, and something seemed a bit off in the join example:  
https://www.crecto.com/crecto-repo-query#join

Where does the `:image` come from, what does it mean? How are `users` and `user_tags` indicated in the Crystal code?

Cheers,
mmKALLL

**Comment by fridgerator** [comment]
Thanks for pointing this out @mmKALLL 

Fixed here: https://github.com/Crecto/docs/commit/da033205154989743ffbee3b4bb69c8e60ed6be9
